### ISSUE TITLE
[Feature Request] Add support for LinkedIn

### ISSUE THREAD

**Issue by twcau** [zevnda/workforce-mate#1]
**Summary:**
Request to add support for LinkedIn Jobs URL’s to the browser plug-in.

**Example URL’s:**
- https://www.linkedin.com/jobs/view/4019424837
- https://www.linkedin.com/jobs/view/4000852784
- https://www.linkedin.com/jobs/view/4017286708

**Comment by twcau** [comment]
I've taken a quick look at your code, and whilst i'm not a full blown programmer (plus I don't want to submit a messed up pull to your repo in case I make the work harder then needed), i've been able to figure out how you're getting the values you need to populate the form.

So to help you with adding LinkedIn support, i've taken a look at the code for a jobs listing there and am pretty sure i've identified the DOM elements you need to look for when parsing the page for values to extract and populate.

This is based on https://www.linkedin.com/jobs/view/4019424837; and have validated this against the other example links provided to be comfortable this will be consistent.

- jobTitle:
  - H3 with DIV class named sub-nav-cta__header
  - Example code: 
    `<h3 class="sub-nav-cta__header">IT Support Helpdesk and On-site Support</h3>`
- jobLocation:
  - SPAN class named sub-nav-cta__meta-text
  - Example code:
  `<span class="sub-nav-cta__meta-text">Perth, Western Australia, Australia</span>`
- jobAgent (and this one was tricky)
  - either the TITLE attribute, or contents of linked text, for A HREF with class name sub-nav-cta__optional-url
  - Example code:
  `<a href="[https://au.linkedin.com/company/trucell?trk=public_jobs_sub-nav-cta-optional-url](view-source:https://au.linkedin.com/company/trucell?trk=public_jobs_sub-nav-cta-optional-url)" class="sub-nav-cta__optional-url" title="Trucell" data-tracking-control-name="public_jobs_sub-nav-cta-optional-url" data-tracking-will-navigate>Trucell</a>`

**Comment by zevnda** [comment]
Awesome work mate. Feel completely free to submit a PR with your changes if you'd like to. More than happy to let you take a shot at it yourself, and I'll review the changes and either advise further changes, or fix them myself, totally up to you. Seems like you know what you're doing.

**Comment by zevnda** [comment]
Didn't hear back from you regarding this, so I went ahead and added support for LinkedIn in `1.2.2` with 5638ddbdacebc73b3dc9b84e00d59fff79a146e6
