### ISSUE TITLE
[Bug] Firefox - Unable to install manually, package corruption error

### ISSUE THREAD

**Issue by twcau** [zevnda/workforce-mate#2]
### Affected version
1.1.0

### Error message
about:addons
This add-on could not be installed because it appears to be corrupt.

![image](https://github.com/user-attachments/assets/f67fb0d9-dca3-4ea3-8a2a-3b8b2c89fe72)

### Steps to replicate

1. Downloaded latest release.
2. Navigate to about:addons.
3. Select Tools for all add-ons > Install Add-on from file.
4. Select .zip file downloaded from latest release in select file dialogue.
5. Identified error message displayed.

### Workarounds attempted

1. Navigate to about:debugging#/runtime/this-firefox.
2. Select Temporary Extensions > Load Temporary Add-on.
3. Select .zip file downloaded from latest release in select file dialogue.
4. Plug-in loads, navigate to https://www.workforceaustralia.gov.au/individuals/obligations/my-job-search-effort
5. Select Add a job.

Result: Plugin loads, and listing URL field displays.

### Debugging information

Observed in Firefox version(s): 127.0 (64-bit), 130.0 (64-bit)
Observed in OS: Windows 11 Pro, 23H2 Release, OS Build 22635.4145

**Comment by twcau** [comment]
Also affects version 1.2.0.

**Comment by zevnda** [comment]
The `firefox` version downloaded from the latest releases page is not a signed extension, so there is a different method to loading it. There is a written and video guide showing those steps in the README.

Once the extension is published on Mozilla Add-ons, I believe I can download the `.xpi` file and package it in the release, and this will solve that issue _(need to look in to that further)_
